### ISSUE TITLE
Tracking Issue: Cask Tap Migration

### ISSUE THREAD

**Issue by reitermarkus** [Homebrew/brew#4193]
Checklist:

- [x] Add migration code. (https://github.com/Homebrew/brew/pull/4174)
- [x] Move taps from `caskroom` to `Homebrew`.
- [x] Activate migration code. (https://github.com/Homebrew/brew/pull/4195)
- [x] Update URLs and paths pointing to old locations.
- [x] Update `tap_migration.json` in `homebrew/core`. (https://github.com/Homebrew/homebrew-core/pull/28277)
- [x] Remove unneeded `caskroom` references. (https://github.com/Homebrew/brew/pull/4210)

**Comment by MikeMcQuaid** [comment]
Nice work @reitermarkus! 👏
