### ISSUE TITLE
Tracking Issue: Integrating `brew cask search` into `brew search`

### ISSUE THREAD

**Issue by reitermarkus** [Homebrew/brew#4254]
Checkpoints:

 - [x] Refactor `brew search`. (https://github.com/Homebrew/brew/pull/4253)
 - [x] Refactor `brew cask search`. (https://github.com/Homebrew/brew/pull/4306)
 - [x] Discuss behaviour.
 - [x] Integrate `brew cask search` into `brew search`. (https://github.com/Homebrew/brew/pull/4316)
 - [x] Allow searching Casks by `name` (https://github.com/Homebrew/brew/pull/4316).
 - [x] Redirect `brew cask search` and add deprecation warning (https://github.com/Homebrew/brew/pull/4316).
 - [x] Remove documentation for `brew cask search` (https://github.com/Homebrew/homebrew-cask/pull/48666, https://github.com/Homebrew/brew/pull/4356).

**Comment by reitermarkus** [comment]
Regarding the behaviour:

Without any options, I think the best way would be to output this:

```
==> Formulae:
foo bar
==> Casks:
baz
```

When the output is not a TTY, don't print the headlines and use the long versions for Casks. Alternatively, don't treat TTY differently, since we currently also don't really support piping output to another command:

```
==> Searching local taps...
==> Searching taps on GitHub...
```

If we choose to not support piping output, I don't see a need for a `--cask`/`--formula` flag to only search for one specific thing.

**Comment by MikeMcQuaid** [comment]
> Alternatively, don't treat TTY differently, since we currently also don't really support piping output to another command

👍 to this when passing a parameter from me; we've not had any asks for this.

`brew search` without argument should output just formulae, though. It may be annoying or inconsistent but there are many, many uses in the wild with this assumption that we don't want to break.

**Comment by JCount** [comment]
I strongly agree regarding what `brew search`'s behavior needs to be.

It also probably will not be that difficult for users to accommodate, 🤞.

**Comment by reitermarkus** [comment]
Another thing to discuss:

`brew cask search` creates a simplified search term, i.e. trimming all non-word and non-digit characters from both the query and the Cask tokens.

`brew search` does not do that.

So, for example, `brew cask search eid` matches

 - `cocos-code-ide` (cocoscod**eid**e)
- `eclipse-ide` (eclips**eid**e)
- `kaleidoscope` (kal**eid**oscope)
- `liteide` (lit**eid**e)

I think we should do the same for `brew search`.

**Comment by reitermarkus** [comment]
> Can you point to any e.g. search engines that have similar behaviour?

I'm no search engine expert, but I also can't point to a search engine *not* doing it.

Anyways, I have no strong opinion on this, but here is a more useful example:

Before:

```
$ brew search qt5
pyqt5 qt5
```

After:

```
$ brew search qt5
pyqt5 qt5 qt@5.11 qt@5.5
```

**Comment by JCount** [comment]
I think `brew search` already provides similar functionality in its ability to handle regex.

**Comment by MikeMcQuaid** [comment]
> I'm no search engine expert, but I also can't point to a search engine not doing something like that.

Can you provide some e.g. search engine links to demonstrate this?

**Comment by reitermarkus** [comment]
https://www.google.com/search?q=rubo-cop
https://github.com/search?q=rubo-cop
https://duckduckgo.com/?q=rubo-cop

All find `rubocop` without a `-`.

**Comment by MikeMcQuaid** [comment]
> https://www.google.com/search?q=rubo-cop
> https://github.com/search?q=rubo-cop
> https://duckduckgo.com/?q=rubo-cop
> 
> All find rubocop without a -.

Cool thanks 👍 



> I'll let you both make a final decision here so we can proceed.

I'm 👍 on the trimming of non-word/digit characters.

**Comment by JCount** [comment]
> I'm 👍 on the trimming of non-word/digit characters.

👍

**Comment by yurikoles** [comment]
I see that now there is duplicates in search results:

```
brew cask search virtualbox
==> Matches
virtualbox                                           virtualbox-beta                                      virtualbox-extension-pack                            virtualbox-extension-pack-beta
==> Remote Matches
homebrew/cask-versions/virtualbox-beta                                                                    homebrew/cask/virtualbox
homebrew/cask-versions/virtualbox-extension-pack-beta                                                     homebrew/cask/virtualbox-extension-pack
```

**Comment by JCount** [comment]
@yurikoles `brew cask search` is still in the process of being merged into `brew search`, so that should just be a temporary issue during the transition. (🤞)

**Comment by reitermarkus** [comment]
Done.

**Comment by wickles** [comment]
This broke one of my scripts for interfacing with `brew-cask`. I need the functionality for `brew cask search` without arguments where all Casks are listed. Now it shows all brew formulae and no Casks. Is there an alternative method that I can use to list all Casks (or analogously, all formulae from a specific tap)?

**Comment by laughedelic** [comment]
> This broke one of my scripts for interfacing with brew-cask. I need the functionality for brew cask search without arguments where all Casks are listed.

Same here: https://github.com/laughedelic/brew-completions/issues/4. I think it still needs a `--cask` flag to list only casks.
