### ISSUE TITLE
Tracking Issue: Merging download strategies.

### ISSUE THREAD

**Issue by reitermarkus** [Homebrew/brew#4401]
Checklist:

- [x] Separate staging from downloads. (https://github.com/Homebrew/brew/pull/4402)
- [x] Refactor cask staging strategies. (https://github.com/Homebrew/brew/pull/4474, https://github.com/Homebrew/brew/pull/4479)
- [x] Merge staging strategies (https://github.com/Homebrew/brew/pull/4541).
- [x] Refactor download strategies. (https://github.com/Homebrew/brew/pull/4592, https://github.com/Homebrew/brew/pull/4593, https://github.com/Homebrew/brew/pull/4595, https://github.com/Homebrew/brew/pull/4596, https://github.com/Homebrew/brew/pull/4662)
- [x] Merge download strategies. (https://github.com/Homebrew/brew/pull/4607, https://github.com/Homebrew/brew/pull/4608, https://github.com/Homebrew/brew/pull/4616)

**Comment by MikeMcQuaid** [comment]
I think this is now all done? Congrats @reitermarkus 👏
