### ISSUE TITLE
Tracking Issue: Merging `brew cleanup` and `brew cask cleanup`.

### ISSUE THREAD

**Issue by reitermarkus** [Homebrew/brew#4660]
Checklist:

- [x] Refactor `brew cleanup`. (https://github.com/Homebrew/brew/pull/4633, https://github.com/Homebrew/brew/pull/4635, https://github.com/Homebrew/brew/pull/4651)
- [x] Merge `brew cask cleanup` into `brew cleanup`. (https://github.com/Homebrew/brew/pull/4639)
- [x] Deprecate `brew cask cleanup`. (https://github.com/Homebrew/brew/pull/4645)
- [x] Extend `brew cleanup`. (https://github.com/Homebrew/brew/pull/4647, https://github.com/Homebrew/brew/pull/4651, https://github.com/Homebrew/brew/pull/4667)

**Comment by MikeMcQuaid** [comment]
This is done I think, nice work @reitermarkus!
