### ISSUE TITLE
HackIllinois 2020 formula upgrade issue tracker

### ISSUE THREAD

**Issue by chenrui333** [Homebrew/brew#7095]
- [ ] abook
- [ ] abyss
- [ ] advancemenu
- [ ] adwaita-icon-theme
- [ ] agedu
- [ ] aliyun-cli
- [ ] amazon-ecs-cli
- [ ] amqp-cpp
- [ ] ansible
- [ ] aom
- [ ] aqbanking
- [ ] arangodb
- [ ] aravis
- [ ] archi-steam-farm
- [ ] arm-linux-gnueabihf-binutils
- [ ] arx-libertatis
- [ ] astrometry-net
- [ ] atk
- [ ] atkmm
- [ ] auditbeat
- [ ] autopsy
- [ ] awsume
