### ISSUE TITLE
brew bump-cask-pr changes requested by homebrew-cask maintainers

### ISSUE THREAD

**Issue by SeekingMeaning** [Homebrew/brew#9466]
- [x] Should work for SHA-only changes https://github.com/Homebrew/homebrew-cask/issues/93013

  ```sh
  brew bump-cask-pr securityspy --sha256 'de66546630615deb1bae58b54a3fc5f6bb29ec674c770c721b3245a29fad00cf' --write
  ```

- [ ] Should not consider closed PRs when looking for duplicates https://github.com/Homebrew/homebrew-cask/issues/93014

- [x] Should not add a checksum when a cask is versioned and has `:no_check` https://github.com/Homebrew/homebrew-cask/issues/94942

  ```sh
  brew bump-cask-pr sensei --version '1.3.2,74' --write
  ```

- [x] Should ignore downgrades https://github.com/Homebrew/homebrew-cask/issues/94944

  ```sh
  brew bump-cask-pr sensei --version '1.3.2,74' --write
  ```

**Comment by xxyzz** [comment]
I was using `brew bump-cask-pr --version 10.0.7 tor-browser` on d73fc480a and get the following error:

```
...
==> Downloading https://dist.torproject.org/torbrowser/10.0.7/TorBrowser-10.0.7-osx64_zh-TW.dmg
######################################################################## 100.0%
Warning: Cannot verify integrity of '03364e9173a786dc05fb1c643e4ec1934f71a21d3b7ea71ad855b8658fbc0481--TorBrowser-10.0.7-osx64_zh-TW.dmg'.
No checksum was provided for this resource.
For your reference, the checksum is:
  sha256 "7392c972dde595326575a93a748c934fafa2f33bd8ed94681f179602bcd7c0b8"
==> replace /version\s+["']10\.0\.6["']/m with "version \"10.0.7\""
==> replace "2287d8a89bf31238202ec4eca6e93dcfb3a9a702628c57247743897d90cf85d2" with "606a6e874f83ef2782c843108bdcb239a2d928852b74c
...
==> replace "80bca47bb96be730c4e32d4e653f76207cba9f1ef45aecb4ce875d49503c7383" with "7392c972dde595326575a93a748c934fafa2f33bd8ed9
==> replace /sha256\s+["']77bf71c7e1e547de0bab1994c792dffa2fde4d1cea064270e05dd4e9fd6264e0["']/m with "sha256 \"aad168a4fa11ee9975
Error: inreplace failed
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask/Casks/tor-browser.rb:
  expected replacement of /sha256\s+["']77bf71c7e1e547de0bab1994c792dffa2fde4d1cea064270e05dd4e9fd6264e0["']/m with "sha256 \"aad168a4fa11ee9975474ce6b04d2a4514195b82fd71d96e20db4da9395d83a7\""
```
